### PR TITLE
Monica login 2

### PR DESCRIPTION
**Pull request by monivg**
Now we can create an account, have an encoded password saved in MySQL. After creating account it sends you to create an event. Still working on logging into existing account.

### CODE REVIEW

**Comment by jghilliard** [comment]
It works for me.  It runs and I can create accounts through user/host and events through events/create

**Review by jghilliard — APPROVED** [review]
I approve, this will help me pass user information to the controllers I'm working on.

**Review by LaShundra — APPROVED** [review]
This worked for me. Looks good.

**Review by LightningFrisk — APPROVED** [review]
Pulled this down on my machine and it added user/pass hash to database w/o issues.

**Pull request merged**
