### PR TITLE
user controller to create account - is checking for validations and c…

### PR DESCRIPTION
**Pull request by monivg**
Code is working and saving data in MySQL - need to add alerts for validation

### CODE REVIEW

**Review by LightningFrisk — APPROVED** [review]
works great, validation too strict

**Comment by LaShundra** [comment]
Looking good. This worked for me with no issues.

**Review by LaShundra — APPROVED** [review]

**Comment by jghilliard** [comment]
Sorry group, I didn't realize I was added directly as a reviewer.  Approved.

**Review by jghilliard — COMMENTED** [review]
Sorry group, I didn't realize I was added directly as a reviewer. Approved.

**Pull request merged**
